#!/usr/bin/env node
'use strict'

const getData = require('../lib/get-data')
const parseNewick = require('./parser')
const prettyPrintNewickTree = require('./printer')

function main() {
	let file = process.argv[2]

	if (!file && process.stdin.isTTY) {
		console.error('usage: hyb-newick-pretty (<input> | -)')
		process.exit(1)
	}

	return getData(file)
		.then(parseNewick)
		.then(prettyPrintNewickTree)
		.then(console.log)
		.catch(console.error)
}

if (require.main === module) {
	main()
}
