#!/usr/bin/env node
'use strict'

const getData = require('../../lib/get-data')
const beast = require('./index')

function main() {
	let argv = process.argv.slice(2)
	let file = argv[0]

	if (!file && process.stdin.isTTY) {
		console.error('usage: hyb-beast (<input> | -)')
		process.exit(1)
	}

	return getData(file)
		.then(beast)
		.then(console.log)
		.catch(console.error)
}

if (require.main === module) {
	main()
}
