#!/usr/bin/env node
'use strict'

const getData = require('../lib/get-data')
const fastaToBeast = require('./fasta-to-beast')

function main() {
	let file = process.argv[4]

	if (!file && process.stdin.isTTY) {
		console.error('usage: hyb-fasta-to-beast --name (<input> | -)')
		process.exit(1)
	}

	return getData(file)
		.then(data => fastaToBeast(data, process.argv[3]))
		.then(console.log)
		.catch(console.error)
}

if (require.main === module) {
	main()
}
