#!/usr/bin/env node
'use strict'

const getData = require('../lib/get-data')
const fastaToNexus = require('./fasta-to-nexus')

function main() {
	let file = process.argv[2]

	if (!file && process.stdin.isTTY) {
		console.error('usage: hyb-fasta-to-nexus (<input> | -)')
		process.exit(1)
	}

	return getData(file)
		.then(fastaToNexus)
		.then(data => console.log(data))
		.catch(console.error.bind(console))
}

if (require.main === module) {
	main()
}
